# Generated by Django 5.0 on 2023-12-11 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="is_active",
        ),
    ]
