# Generated by Django 5.0 on 2023-12-13 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts_app", "0002_remove_contact_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="notes",
        ),
    ]
